name: taxtds

networks:
  default:
    name: taxtds

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # volumes:
    #   - .:/app
    ports:
      - 4000:5000
    command: node .
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: genos
      MONGO_INITDB_ROOT_PASSWORD: genos
      MONGO_INITDB_DATABASE: taxtdsdb
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongoDb:/data/db
