name: bizmate

networks:
  default:
    name: bizmate

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 5000:4000
    command: NODE_ENV=production node .
    depends_on:
      - mongodb

  

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: genos
      MONGO_INITDB_ROOT_PASSWORD: genos
      MONGO_INITDB_DATABASE: bizmatedb
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongoDb:/data/db

 